### ISSUE TITLE
The kinetic release does not have debian tags

### ISSUE THREAD

**Issue by tfoote** [tork-a/geneus-release#1]
This is failing on our test farm. 

Make sure to have the latest version of bloom (0.5.21)  and allow it to update the tracks for release. https://github.com/ros-infrastructure/bloom/commit/5305e9749e17a2162939c4f29d2400e216fe94cb

There should be an extra line inserted here: https://github.com/tork-a/geneus-release/blob/master/tracks.yaml#L75

Like https://github.com/ros-gbp/ros_comm-release/blob/master/tracks.yaml#L114

**Comment by tfoote** [comment]
An example of the failure is here: http://54.183.26.131:8080/view/Kbin_debianjessie64/job/Ksrc_debianjessie__geneus__debian_jessie__source/206/console

```
00:00:09.473 Invoking 'git clone --branch debian/ros-kinetic-geneus_2.2.5-0_jessie --depth 1 --no-single-branch https://github.com/tork-a/geneus-release.git /tmp/sourcedeb/source'
00:00:09.475 Cloning into '/tmp/sourcedeb/source'...
00:00:09.958 fatal: Remote branch debian/ros-kinetic-geneus_2.2.5-0_jessie not found in upstream origin
00:00:09.959 # END SUBSECTION
```

**Comment by tfoote** [comment]
@jacquelinekay I linked this into the kinetic kickoff checklist: https://github.com/ros/rosdistro/issues/9945

**Comment by k-okada** [comment]
sorry for trouble
fixed in
https://github.com/tork-a/geneus-release/commit/ec2baca94e46f5293a4f10f0fb5872573cb6e22f
and update  https://github.com/ros/rosdistro/pull/10726

## 

◉ Kei Okada

**Comment by tfoote** [comment]
Awesome. Thanks for the quick fix! It has passed already. http://54.183.26.131:8080/view/Ksrc_debianjessie/job/Ksrc_debianjessie__geneus__debian_jessie__source/219/
